networks:
  ikun-net:
    name: ikun-net
services:
  app-admin:
    build:
      context: .
      dockerfile: DockerFile
    container_name: app-admin
    ports:
      - 8080:8080
    networks:
      - ikun-net
    volumes:
      - ./data/logs/:/home/ikun/logs

#  mysql:
#    image: 'mysql:latest'
#    environment:
#      - 'MYSQL_DATABASE=mydatabase'
#      - 'MYSQL_PASSWORD=secret'
#      - 'MYSQL_ROOT_PASSWORD=verysecret'
#      - 'MYSQL_USER=myuser'
#    ports:
#      - '3306'
  redis:
    container_name: redis
    image: redis:latest
    ports:
      - 6379:6379
    environment:
      - REDIS_PASSWORD="@Ikun1991"
    command: redis-server --requirepass @Ikun1991
    volumes:
      - ./data/redis/redis.conf:/usr/local/etc/redis/redis.conf
    restart: always
    networks:
      - ikun-net
