networks:
  ikun-net:
    name: ikun-net
    driver: bridge
services:
  app-admin:
    depends_on:
      - redis
#      - mysql8
    build:
      context: .
      dockerfile: DockerFile
    container_name: app-admin
    ports:
      - 8080:8080
    networks:
      - ikun-net
    volumes:
      - ./app/logs/:/home/ikun/logs
    environment:
      DATABASE_URL: host.docker.internal
      DATABASE_PORT: 3306
      DATABASE_USER: liliu
      DATABASE_PASSWORD: '@Ikun1990'
      DATABASE_NAME: liliu
#  mysql8:
#    hostname: mysql8
#    image: mysql:8.0.24
#    restart: no
#    build:
#      context: .
#    container_name: mysql8
#    privileged: true
#    environment:
#      MYSQL_ROOT_PASSWORD: c4ca4238a0b923820dcc509a6f75849b
#      MYSQL_DATABASE: liliu
#      MYSQL_USER: liliu
#      MYSQL_PASSWORD: '@Ikun1990'
#    command:
#      --character-set-server=utf8mb4
#      --collation-server=utf8mb4_general_ci
#      --explicit_defaults_for_timestamp=true
#      --default-authentication-plugin=mysql_native_password
#    networks:
#      - ikun-net
#    ports:
#      - 3300:3306
#    volumes:
##      - ./mysql:/var/lib/mysql:/var/lib/mysql/
#      - ./mysql/conf:/etc/mysql/conf.d
#      - ./mysql/logs:/logs
#      - ./init.sql:/init.sql

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - 6300:6300
    environment:
      - REDIS_PASSWORD="@Ikun1991"
    command: redis-server --requirepass @Ikun1991
    volumes:
      - ./data/redis/redis.conf:/usr/local/etc/redis/redis.conf
    restart: always
    networks:
      - ikun-net
